### ISSUE TITLE
Prio 2-->Mis tareas: Pre carga de datos / Inspección en PCC: Que agregue automáticamente la patente del térmico.

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/DDPE-tools-pro#204]
Ambiente de TestingSicpoa - v2.2.13
_Credenciales:_
URL: https://testingsicpoa.sanjuan.gob.ar/traz-tools/
usr: obarbano@sanjuan.gov.ar
pass: 12345

**Descripción:**
Se requiere tanto en la instancia de "Pre-carga de datos" como en la de "Inspección en PCC" que el sistema agregue automáticamente la patente del térmico.

https://github.com/Trazalog/DDPE-tools-pro/assets/88331456/2850790e-2220-4743-901e-0e8630a6fae3

**Comment by gnicolia-trazalog** [comment]
Solucionado en v2.2.16
