### ISSUE TITLE
Proceso de negocios-->Ingreso Barrera-->Botón "Imprimir Acta Reprecintado": que recupere el Nro de acta & los datos del permiso

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/DDPE-tools-pro#231]
Ambiente Testingsicpoa - v2.3.3

**Descripción:**
Al abrir el acta desde el botón "imprimir acta Reprecintado" no está recuperando los datos del permiso cargado en el formulario de reprecintado

Se adjunta una imagen

![image](https://github.com/Trazalog/DDPE-tools-pro/assets/88331456/5a867b09-506a-4ca7-85c6-a2b39a6b60df)

Y en lo posible que figure el número de acta

(Activar audio)

https://github.com/Trazalog/DDPE-tools-pro/assets/88331456/fe78715b-c2b1-4742-8b66-26714a03844f

**Comment by jfernandez-trazalog** [comment]
Pablo M.

**Comment by floto-trazalog** [comment]
Solucionado en v2.3.3.1
