### ISSUE TITLE
Procesos de negocios-->Ingreso en barrera: que el botón de "Imprimir el acta de Reprecintado" se mantenga  

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/DDPE-tools-pro#232]
Ambiente Testingsicpoa - v2.3.3

**Descripción:**
Al pasar la instancia de reprecintado el sistema elimina el botón y el usuario no puede acceder al acta de Reprecintado

![image](https://github.com/Trazalog/DDPE-tools-pro/assets/88331456/1bf008c2-44fa-49f9-8eb6-5737731259bd)

Como se indica en la imagen, los registros señalados tienen generadas actas de reprecintado, pero el sistema solo recupera el botón cuando el camión se presenta con estado: _Reprecintado_ y lo correspondiente sería que se pueda visualizar el acta en otro momento

**Comment by jfernandez-trazalog** [comment]
Pablo M.

**Comment by floto-trazalog** [comment]
Solucionado en v2.3.4
