### ISSUE TITLE
SOPORTE-->Procesos de negocios-->Inspección en Barrera/Rep. Histórico: que el acta común guarde la fecha y hora del momento en que se genera

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/DDPE-tools-pro#233]
Ambiente test - v2.3.3

**Descripción:**
Al momento, de grabar un Re-Precintado, el sistema está mezclando las fechas y horas en el acta comun, y lo correspondiente, sería que se dieferencien los respectivos datos en las diferentes pantallas:

* Inspección en barrera

_video con audio_

https://github.com/Trazalog/DDPE-tools-pro/assets/88331456/f57b9982-d0f9-4049-904c-110799b6983a

También, que se diferencien 
* Rep. Hist Camiones

![image](https://github.com/Trazalog/DDPE-tools-pro/assets/88331456/38376f98-51ca-40e9-8e56-4638bac1248b)

**Comment by jfernandez-trazalog** [comment]
Pablo M.

**Comment by floto-trazalog** [comment]
Solucionado en v2.3.4
