### ISSUE TITLE
SOPORTE-->Procesos de negocios-->Ingreso en Barrera & Rep Hist Camiones: modificar y recuperar datos de las respectivas actas

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/DDPE-tools-pro#234]
Ambiente Testingsicpoa - v2.3.3

**Descripción:**
Al presionar los botones "Imprimir acta" e "Imprimir acta Reprecintado" surgen las siguientes modificaciones:

### 1) En el 1er párrafo del **Acta común** y **Acta de Re-Precintado** 
se recomienda quitar la oración indicada en la imagen y reemplazar por "DDP"

![image](https://github.com/Trazalog/DDPE-tools-pro/assets/88331456/c35b7c61-6d8e-4207-8c9d-6be8da43acf1)

### 2) En el 2do párrafo del **Acta de Re-Precintado**  
que recupere el producto seleccionado al completar dicho formulario

![image](https://github.com/Trazalog/DDPE-tools-pro/assets/88331456/3ef62dfe-923c-41c6-9244-7a1208882dc9)

### 3) En el 2do párrafo del **Acta común** 
hoy recupera los permisos de la Inspección **+** del Re-Precintado, lo correspondiente, sería que recupere, únicamente, los permisos ingresados en el form de la **Inspección en PCC**

![image](https://github.com/Trazalog/DDPE-tools-pro/assets/88331456/a29ccf92-12a5-4038-84ab-675634fe0c79)

_zoom_

![image](https://github.com/Trazalog/DDPE-tools-pro/assets/88331456/82a2f107-ef80-401b-9c86-223e37d5d8ad)

### 4) En el 3er párrafo del **Acta de Re-Precintado** 
Que recupere los precintos ingresados en el form del Re-Precintado

![image](https://github.com/Trazalog/DDPE-tools-pro/assets/88331456/ab4c6206-cda3-40c9-8c5b-3c0e94a27d07)

**Comment by jfernandez-trazalog** [comment]
Pablo M.

**Comment by floto-trazalog** [comment]
Solucionado en v2.3.5
