### ISSUE TITLE
Procesos de negocio-->Ingreso por Barrera-->Imprimir Acta: que recupere los datos cargados en el formulario de la  infracción que se generó al momento de la infracción

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/DDPE-tools-pro#236]
Ambiente Testing - v2.3.3.1

**Descripción:**
Al imprimir el acta desde la pantalla de Inspección por barrera 

* En el 1er Párrafo: 
No está recuperando la hora con el formato correcto, lo correspondiente sería que muestre la hora en que se imprime el acta, por ejemplo: "16:24 horas." (como se indica en la imagen)

* En el 2do Párrafo: 
Que recupere el producto seleccionado en el formulario como se marca en la imagen

* En el último Párrafo: 
Que recupere la hora ingresada  en el formulario en el formulario

![image](https://github.com/Trazalog/DDPE-tools-pro/assets/88331456/9dc36815-c666-44cf-b57d-dad4df4dde55)

**Comment by jfernandez-trazalog** [comment]
Pablo M.

**Comment by floto-trazalog** [comment]
Solucionado en v2.3.5
