### ISSUE TITLE
SOPORTE-->Bandeja de tareas-->Alerta camión que no pasó por PCC: que se apliquen las mismas condiciones en el form

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/DDPE-tools-pro#237]
Ambiente testing - v2.3.4

**Descripción:**
En "Alerta de Camión que no pasó por PCC" correspondería aplicar los sigueintes cambios:

### 1) En el form de Permiso de tránsito:
está mostrando el campo _Kilos_ y lo conveniente sería quitar dicho campo

![image](https://github.com/Trazalog/DDPE-tools-pro/assets/88331456/53b4f6fd-b56d-4cd8-96ab-1deb8589d037)

### 2) En el form de Infracción:
existen campos obligatorios que el usuario final no tiene, lo oprtuno sería quitar el máximo de campos obligatorios dejándolos como opcionales (ídem que en el formulario de Infracción en PCC)

![image](https://github.com/Trazalog/DDPE-tools-pro/assets/88331456/72b290ff-e2d0-4b41-88cb-4b53e14d3957)

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.

**Comment by floto-trazalog** [comment]
Solucionado en v2.3.5
