### ISSUE TITLE
SOPORTE-->Bandeja de tareas-->Pre-carga de datos & Inspección en PCC & Alerta de camión que no pasó por PCC: que la patente del tractor esté vacía

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/DDPE-tools-pro#239]
Ambiente de testing - v2.3.4

**Descripción:**
Al completar los campos de los formularios, está vinculado el campo Patente Tractor con el campo Patente Térmico, el usuario solicita que el campo "Tractor" quede vacío para que él mismo ingrese los datos, es decir, quitar el autocompletado del campo Patente Tractor. Esto se deberá reflejar tanto para el sector de:
* Pre-carga, 
* Inspección en PCC y 
* Alerta de Camión que no pasó por PCC

Video con audio

https://github.com/Trazalog/DDPE-tools-pro/assets/88331456/d04d0506-8416-4490-8b9e-03e7aba4f288

**Comment by jfernandez-trazalog** [comment]
Gerardo R.

**Comment by floto-trazalog** [comment]
Solucionado. en v2.3.5
