### ISSUE TITLE
Bandeja de tareas-->Alerta de camión que no pasó por PCC: Asociar la empresa destino al permiso de tránsito & otros

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/DDPE-tools-pro#240]
Ambiente testing sicpoa - v2.3.4

**Descripción:**
### 2) Modificar el formulario de la Empresa destino,
 quedando asociada al formulario del Permiso de tránsito, tal y como figura en la Pre-carga de datos y en Inpección en PCC

### 3) Validar que para un permiso se puedan grabar varias Empresas Destino,
esto quiere decir que para un mismo Nro de permiso de tránsito me permita agregar varias empresas destino
_por ejemplo: media res con destino al VEA y carne de cerdo con destino a Atomo_

https://github.com/Trazalog/DDPE-tools-pro/assets/88331456/d999d133-3857-40bc-8e3b-be69a826586b

### 4) Validar que no se repita el Nro de permiso de tránsito
A su vez, relacionado con el ítem anterior, solo permita cargar al usuario un único permiso de tránsito y sería oportuno, mostrar en pantalla el aviso de alerta en el caso que se repita el Nro.

### 5) Que al imprimir el acta, se guarden los datos correspondientes a la misma en: 
* la vista previa,
* Ingreso por Barrera
* Re. Hist de camiones

**Importante:** que el formato del acta sea similar a lo pedido en las actas de Inspección en PCC

_Se deja como ejemplo el formato de un acta de Inspección en PCC:_

![image](https://github.com/Trazalog/DDPE-tools-pro/assets/88331456/2c543534-863f-4464-8c0d-e4e5c0946c72)

### 6) No está recuperando la patente del térmico y,
lo correspondiente es que recupere la patente del térmico ingresada en el Ingreso por Barrera

![image](https://github.com/Trazalog/DDPE-tools-pro/assets/88331456/97f05238-edd8-4f9e-a649-13623ab8f4d3)

**Comment by jfernandez-trazalog** [comment]
Pablo M.

**Comment by floto-trazalog** [comment]
Solucionado en v2.3.5
