### ISSUE TITLE
Inpección en Barrera-->Botón de Imprimir Acta: que figuren los datos correspondientes en el acta común

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/DDPE-tools-pro#241]
Ambiente de testing - v2.3.4

**Descripción:**
Al completar el Acta de Re-precintado se graban los datos correctamente, 
Luego, al revisar el _Acta común_ desde la pantalla de "Inspección por barrera" o por "Rep. Hist. de Camiones" se observa que recupera datos ingresados en el formulario del Re-precintado y lo conveniente sería que figuren los datos que pertenecen al sector de Inpección en PCC, es decir, los del _Acta común_

![image](https://github.com/Trazalog/DDPE-tools-pro/assets/88331456/c7d6ffd2-fe45-4b4e-9599-b2be14475a73)

**Comment by jfernandez-trazalog** [comment]
Gerardo R.

**Comment by floto-trazalog** [comment]
Solucionado en v2.3.5
