### ISSUE TITLE
Inpección en Barrera-->Botón de Imprimir Acta: que figure el Nro. de acta común

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/DDPE-tools-pro#242]
Ambiente testing - v2.3.4

**Descripción**:
Al rescatar el _Acta común_ desde la pantalla de Inspección en Barrera o desde Rep. histórico de camiones el sistema está reescribiendo el Nro de Acta de _Re-precintado_ y lo correspondiente es que figure el número anterior, el correspondiente al Nro. de Acta común. 
 como se observa en la iamgen

![image](https://github.com/Trazalog/DDPE-tools-pro/assets/88331456/9a070cb7-c5f9-456a-9af0-ba9d6506eed4)

**Comment by jfernandez-trazalog** [comment]
Gerardo R.

**Comment by floto-trazalog** [comment]
Solucionado en v2.3.6
