### ISSUE TITLE
SOPORTE-->Bandeja de tareas-->Alerta camión que no pasó por PCC-->Cargar Nueva empresa transporte: agregar nueva empresa 

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/DDPE-tools-pro#243]
Ambiente testing - v2.3.4

**Descripción:** _este requerimiento se detalla en el último correo enviado por el cliente, según mi teoría sucedió a causa de la poca memoria del servidor, porque minutos después se cayó el sistema._

Agregar este dato de forma manual--> "Transportista:" => "Dato Provisorio", luego, una vez avanzada la tarea de ese térmico, probar que la empresa transportista quede cargada en el sistema para utilizarla más adelante, con un nuevo térmico ingresado.
Muchas gracias!

_Se adjunta imagen_

![image](https://github.com/Trazalog/DDPE-tools-pro/assets/88331456/af46bfcd-b875-4239-99f0-39dacb46a33e)

**Comment by jfernandez-trazalog** [comment]
Pablo M.

**Comment by floto-trazalog** [comment]
Se cierra porque el sistema si guarda el dato del transportista
