### ISSUE TITLE
SOPORTE-->Rep Hist. de Camiones-->Filtro: "Patente térmico": al ingresar una patente que recupere los registros 

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/DDPE-tools-pro#244]
Ambiente testingsicpoa - v2.3.6

**Descripción:**
Cuando los usuarios completan los campos obligatorios e ingresan la patente del vehículo térmico utilizando exactamente los mismos caracteres que se guardaron en el "Ingreso por barrera", el sistema no recupera ningún registro. Se espera que el sistema permita a los usuarios filtrar sin importar si las letras están en mayúsculas o minúsculas.

> **Detalles adicionales**

**Impacto:** 
Este problema afecta la capacidad de los usuarios para encontrar registros relevantes, lo que puede llevar a retrasos y confusiones en el proceso.

**Reproducción de la prueba:**
1. En el menú, dar clic en el título Rep. Camiones Histórico
2. Completar ambos campos de "Fecha"
3. Completar el campo "Patente térmico" (ingresando una de las patentes existentes)
4. Clic en el botón "Filtrar"

https://github.com/Trazalog/DDPE-tools-pro/assets/88331456/68071ebf-d816-4ba9-8215-4c4040570128

**Esperado:**
Se espera que el sistema recupere correctamente los registros relevantes sin importar si las letras están en mayúsculas o minúsculas al ingresar la patente del vehículo térmico.
 
**Entorno de trabajo:** Ambiente testingsicpoa - v2.3.6

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.

**Comment by floto-trazalog** [comment]
Solucionado en v2.7.5
