### ISSUE TITLE
Ingreso al sistema: error 504 

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/DDPE-tools-pro#246]
Ambiente Testing siccpoa - 2.3.6

**Descripción:**
Al ingresar el link en el navegador, para ingresar al ambiente, se demora en cargar el sistema y luego, muestra error 504

![image](https://github.com/user-attachments/assets/ae43202a-e388-4850-b8c1-8520a234e21c)

**Observaciones:**
_es probable que se haya caído el servidor o el nginx se desorientó y no redirige.
Tener en cuenta que en nginx no es nuestra responsabilidad, lo más probable es que se haya caído wso2 por procesos repetidos._
By Rodo.

**Comment by jfernandez-trazalog** [comment]
Matías Martín.

**Comment by floto-trazalog** [comment]
Solucionado.
