### ISSUE TITLE
Tareas -> Precarga de Datos: Se puede agregar un permiso de transito sin seleccionar el tipo de doc sanitaria

### ISSUE THREAD

**Issue by Nahuel1705** [Trazalog/DDPE-tools-pro#4]
Descripción: El tipo de documentación sanitaria de un permiso de transito es un dato obligatorio por especificación y el sistema no lo valida

Pasos para reproducir:
1. Seleccionar una tarea de precarga de datos
2. Rellenar los campo del formulario del permiso de transito (Solicitud Nº, Lugar de emisión, Hora de salida, Fecha)
3. Dejar el tipo de doc sanitaria en blanco
4. Presionar el botón "Agregar"

Como sugerencia, cualquiera de las 2 opciones podría estar marcada por defecto y que el usuario la cambie si así lo requiere

![chrome-capture](https://user-images.githubusercontent.com/56811317/124627323-d27e2180-de55-11eb-81eb-40057d7efcfc.gif)

**Comment by aalfaro-trazalog** [comment]
Solucionado en el ambiente de Prueba TEST v1.5.8.5-SICPOA
