### ISSUE TITLE
Evolutivo--> Alerta de camión que no paso por PCC: añadir botón y nomenclador  de Producto/s

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/DDPE-tools-pro#46]
Descripción: El botón añadir "Tipo de Producto" responde a un nomenclador que codifica los nombres de los productos. Debe ser un button seleccionable. Esta información debe estar precargada en el ABM Lista de Valores.

![image](https://user-images.githubusercontent.com/87376576/137764132-e2cb395a-36b9-4d4d-84a0-74e2baf999ab.png)

El usuario selecciona el número de código elegido, y en el campo se muestra el detalle que almacena dicho código.
![image](https://user-images.githubusercontent.com/87376576/137774301-be3462aa-edbd-4850-9bf2-6d928a8bbbd8.png)

Cada código asocia a que especie y grupo pertenece ese alimento
![image](https://user-images.githubusercontent.com/87376576/137766583-6652144b-4a2a-41e8-b539-307e7b5bc048.png)

**Comment by aalfaro-trazalog** [comment]
Esta issue se debe analizar cuando el proyecto se encuentre en la fase evolutiva.

**Comment by floto-trazalog** [comment]
Solucionado en v2.1.16
