### ISSUE TITLE
Tareas -> Precarga de Datos: No cambia el tipo de documentacion sanitaria

### ISSUE THREAD

**Issue by Nahuel1705** [Trazalog/DDPE-tools-pro#5]
Descripcion: Si por cualquier cosa hay un tipo de doc sanitaria seleccionada en el formulario y se decide editar un permiso ya cargado, la doc sanitaria no cambia a la que tiene el permiso

Pasos para reproducir:
1. Seleccionar una tarea de precarga de datos
2. Cargar un permiso con determinado tipo de doc sanitaria
3. Seleccionar el tipo de doc opuesto
4. Presionar el boton editar del permiso cargado anteriormente

![chrome-capture](https://user-images.githubusercontent.com/56811317/124634159-65ba5580-de5c-11eb-972d-7998124808eb.gif)

**Comment by aalfaro-trazalog** [comment]
Actualización 15/09. Ahora al momento de editar una segunda documentación sanitaria, se muestra un alert que indica que ya se está editando un permiso. Hasta no clickear en Agregar, no se puede cambiar el otro doc.

@lbgarcia  esto a nivel funcional, no sé si sería correcto o puede quedar así.

![image](https://user-images.githubusercontent.com/87376576/133509542-c01a61a1-ccea-4c56-b563-6a2d8bc15a52.png)
