### ISSUE TITLE
Tareas -> Precarga de Datos: Se pueden eliminar los permisos de transitos sin quererlo

### ISSUE THREAD

**Issue by Nahuel1705** [Trazalog/DDPE-tools-pro#6]
Descripción: Si presionamos el botón editar de un permiso de transito y luego presionamos el botón editar de otro distinto, el primero se pierde

Pasos para la reproducción:
1. Seleccionar una tarea de precarga de datos
2. Presionar el botón editar de un permiso de transito
3. Presionar el botón editar de un segundo permiso de transito.

![chrome-capture](https://user-images.githubusercontent.com/56811317/124637208-d31bb580-de5f-11eb-8da7-0f5cd50e5486.gif)

Siguiendo los pasos hemos podido eliminar el permiso de Mendoza

**Comment by aalfaro-trazalog** [comment]
@lbgarcia  Sigue ocurriendo en la versión v1.5.8.9

**Comment by aalfaro-trazalog** [comment]
@lbgarcia  En la  v1.5.9 ya se pueden editar los permisos sin que se eliminen. 
La única sugerencia a revisar es que, al dar click en el botón de editar, se genera un aviso "ya se esta editando", y lo muestra dos veces. 
https://user-images.githubusercontent.com/87376576/129397461-36edf8e7-86f8-45d2-978a-1c78ee7e556b.mp4
